# Generated by Django 4.2.15 on 2024-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_degree_remove_user_name_aboutuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='avatar.svg', upload_to='user_images/'),
        ),
    ]
