# Generated by Django 4.2.15 on 2024-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_aboutuser_degree_delete_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='profile_image',
            field=models.ImageField(default='avatar.svg', upload_to='user_images/'),
        ),
    ]
