# Generated by Django 4.2.15 on 2024-11-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_user_profile_image_aboutuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='complete_projects',
            field=models.CharField(max_length=100000000000, null=True),
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='happy_clients',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
