# Generated by Django 5.1.2 on 2024-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_userskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='percentage_knowledge',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
