# Generated by Django 5.1.2 on 2024-11-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_userexperience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExperience',
            new_name='UserX',
        ),
    ]
