# Generated by Django 5.1.2 on 2024-11-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_userexperience_userx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserX',
            new_name='UserExperience',
        ),
    ]
