# Generated by Django 5.1.2 on 2024-11-14 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_userx_userexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
